name: Fork Sync With Upstream

on:
  schedule:
    - cron: '0 7 * * *' # Runs daily at 7 AM UTC
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest from upstream
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Sync with upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: master
          upstream_sync_repo: antiwork/smallbets
